version: "3.8"

services:
    ilc:
        image: kooldev/php:8.1
        container_name: ilc
        working_dir: /ilc
        restart: always
        networks:
            - internal
            - nginx_network
        volumes:
            - ".:/ilc"
            - "./docker/php/php-ini-overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini"
        links:
            - ilc-database
        depends_on:
            - ilc-database
        environment:
            - PHP_EXECUTABLE_PATH=/usr/local/bin/php
    ilc-nginx:
        image: nginx:alpine
        container_name: ilc-nginx
        restart: always
        working_dir: /ilc
        networks:
            - internal
            - nginx_network
        ports:
            - "9005:80"
        volumes:
            - .:/ilc
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - ilc
    ilc-composer:
        image: composer:latest
        container_name: ilc-composer
        working_dir: /ilc
        command: update --ignore-platform-reqs
        volumes:
            - .:/ilc
        restart: on-failure
        depends_on:
            - ilc
    ilc-database:
        image: mariadb:latest
        restart: always
        container_name: ilc-database
        working_dir: /ilc
        networks:
            - internal
            - nginx_network
        command: mysqld --skip-grant-tables
        environment:
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_DATABASE=ilc
            - MYSQL_USER=root
            - MYSQL_PASSWORD=password
        volumes:
            - .:/ilc
            - ./ilc-database:/var/lib/mysql
        ports:
            - "8003:3306"
    ilc-redis:
        image: "redis:alpine"
        ports:
            - "${FORWARD_REDIS_PORT:-6381}:6381"
        volumes:
            - ilc-redis:/data
        networks:
            - internal
            - nginx_network
        command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81

    ilc-npm:
        image: node:20-alpine
        container_name: ilc-npm
        working_dir: /ilc
        volumes:
            - ".:/ilc"
        depends_on:
            - ilc

networks:
    nginx_network:
        external: true
    internal:
        driver: overlay
        name: "global"
        attachable: true
volumes:
    ilc-database:
        driver: local
    ilc-redis:
        driver: local
